mattwhitfield/Unitverse

src/Unitverse.Core.Tests/Models/GenerationResultTests.cs, src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core/CoreGenerator.cs, src/Unitverse.Core/Helpers/DetectedGenerationOptions.cs, src/Unitverse.Core/Models/GenerationResult.cs, src/Unitverse.Core/Models/ModelGenerationContext.cs, src/Unitverse.Core/Options/IGenerationOptions.cs, src/Unitverse.Core/Options/MutableGenerationOptions.cs, src/Unitverse.Core/Strategies/ClassGeneration/AbstractClassGenerationStrategy.cs, src/Unitverse.Specs/ClassBasedStrategySteps.cs, src/Unitverse.Specs/GenerationOptions.cs, src/Unitverse/Commands/GenerateUnitTestsCommand.cs, src/Unitverse/Commands/GenerationItem.cs, src/Unitverse/Helper/Attempt.cs, src/Unitverse/Helper/CodeGenerator.cs, src/Unitverse/Helper/VsMessageBox.cs, src/Unitverse/Options/GenerationOptions.cs, src/Unitverse/Unitverse.csproj
This PR addresses #7 - and allows new tests to be emitted without using the 'Regenerate' option.
It also fixes an issue with custom test class field names and abstract generation.
=> Partial generation

README.md, src/Unitverse.Core.Tests/Options/ConfigExporterTests.cs, src/Unitverse.Core/Options/ConfigExporter.cs, src/Unitverse/IUnitTestGeneratorPackage.cs, src/Unitverse/Options/ExportOptions.cs, src/Unitverse/Options/ExportOptionsControl.Designer.cs, src/Unitverse/Options/ExportOptionsControl.cs, src/Unitverse/Options/ExportOptionsControl.resx, src/Unitverse/UnitTestGeneratorPackage.cs, src/Unitverse/Unitverse.csproj
Adds an options page that contains the functionality to export the config as it is currently configured within Visual Studio. Resolves #12
=> Updates to allow the config to be exported

src/Unitverse.Core.Tests/Helpers/GenerationStatisticsTests.cs, src/Unitverse.Core.Tests/Models/GenerationResultTests.cs, src/Unitverse.Core.Tests/Options/UnitTestGeneratorOptionsFactoryTests.cs, src/Unitverse.Core.Tests/Options/UnitTestGeneratorOptionsTests.cs, src/Unitverse.Core.Tests/Strategies/ValueGeneration/ValueGenerationStrategyFactoryTester.cs, src/Unitverse.Core/CoreGenerator.cs, src/Unitverse.Core/Helpers/AssignmentValueHelper.cs, src/Unitverse.Core/Helpers/Generate.cs, src/Unitverse.Core/Helpers/GenerationContext.cs, src/Unitverse.Core/Helpers/GenerationStatistics.cs, src/Unitverse.Core/Helpers/IGenerationContext.cs, src/Unitverse.Core/Helpers/IGenerationStatistics.cs, src/Unitverse.Core/Models/GenerationResult.cs, src/Unitverse.Core/Options/IUnitTestGeneratorOptions.cs, src/Unitverse.Core/Options/UnitTestGeneratorOptions.cs, src/Unitverse.Core/Options/UnitTestGeneratorOptionsFactory.cs, src/Unitverse.Specs/ClassBasedStrategySteps.cs, src/Unitverse.Specs/MethodBasedStrategySteps.cs, src/Unitverse/Commands/GenerateTestForSymbolCommand.cs, src/Unitverse/Commands/GenerateUnitTestsCommand.cs, src/Unitverse/Helper/CodeGenerator.cs, src/Unitverse/Helper/StatisticsTracker.cs, src/Unitverse/Options/StatisticsOptions.cs, src/Unitverse/Options/StatisticsOptionsControl.Designer.cs, src/Unitverse/Options/StatisticsOptionsControl.cs, src/Unitverse/Options/StatisticsOptionsControl.resx, src/Unitverse/UnitTestGeneratorPackage.cs, src/Unitverse/Unitverse.csproj
Addresses #9 - went with some different stats though
=> Adding statistics collection, just for fun

docs/contributing.md
Fixing a couple of silly errors in the contributing docs
=> Fixing silly documentation errors

src/Unitverse.Core.Tests/Helpers/TestableItemExtractorTests.cs, src/Unitverse.Core/Helpers/TestableItemExtractor.cs, src/Unitverse.Core/Models/ClassModel.cs
Fixes issue with selection of things to generate for - addresses #63
=> Fix for not respecting selected types for generation

src/Unitverse.Core.Tests/Resources/AbstractOutAndRefParams.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/Strategies/ClassGeneration/AbstractClassGenerationStrategy.cs
Fix for out and ref parameters on abstract or protected methods
Addresses #70
=> Fix for out and ref parameters on abstract or protected methods

src/Unitverse/Helper/StatisticsTracker.cs, src/Unitverse/Helper/ZoomTracker.cs, src/Unitverse/Unitverse.csproj, src/Unitverse/Views/ConfigEditorControl.xaml, src/Unitverse/Views/ConfigEditorControl.xaml.cs, src/Unitverse/Views/GenerationDialog.xaml, src/Unitverse/Views/GenerationDialog.xaml.cs, src/Unitverse/Views/SharedResources.xaml
Addresses suggestion made as follow up to #67
=> Slight UI revamp, support for zooming UIs with Ctrl + MouseWheel

README.md, docs/_layouts/default.html
This commit will not create a release.
=> Slight tweaks to documentation template

MarketplaceOverview.md
=> Marketplace documentation link update

docs/_layouts/default.html
Follow up on #82 
No release from this PR
=> Adding favicon link

docs/_layouts/default.html, docs/assets/css/style.scss
=> Documentation layout tweaks

src/Unitverse/Helper/CodeGenerator.cs, src/Unitverse/Properties/Strings.Designer.cs, src/Unitverse/Properties/Strings.resx, src/Unitverse/Resources/ElectiveDisconnectedFileHeader.txt, src/Unitverse/Unitverse.csproj, src/Unitverse/Views/EditableItemTemplateSelector.cs, src/Unitverse/Views/GenerationDialog.xaml, src/Unitverse/Views/GenerationDialog.xaml.cs, src/Unitverse/Views/GenerationDialogViewModel.cs, src/Unitverse/Views/ObjectItemTemplateSelector.cs
Allows you to electively generate a detached file
Addresses #92
=> Detached generation UI

docs/configuration.md, src/Unitverse.Core.Tests/Helpers/InertLoggerTests.cs, src/Unitverse.Core.Tests/Helpers/TargetNameTransformTests.cs, src/Unitverse.Core/Helpers/InertLogger.cs, src/Unitverse.Core/Helpers/TargetNameTransform.cs, src/Unitverse/Helper/ProjectMappingFactory.cs, src/Unitverse/Unitverse.csproj, src/Unitverse/Views/GenerationDialog.xaml.cs, src/Unitverse/Views/GenerationDialogViewModel.cs
Support for specifying multiple target project name patterns
Resolves #101
=> Support for specifying multiple target project name patterns

src/Unitverse.Core.Tests/Resources/ProtectedGenericMethod.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/Strategies/ClassGeneration/AbstractClassGenerationStrategy.cs
Fix for generic protected method emission
Addresses #103
=> Fix for generic protected method emission

src/Unitverse.Core.Tests/Resources/RecordTypeMapping.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/Helpers/InertLogger.cs, src/Unitverse.Core/Strategies/MethodGeneration/MappingMethodGenerationStrategy.cs
Addresses #105 
Re-creating PR due to GitHub weirdness
=> Fix for issue when mapping methods are generated for record types

src/Unitverse.Core.Tests/Resources/NotNullConstraint.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/CoreGenerator.cs
Fix for non type constraints in generic classes - addresses #115
=> Fix for non type constraints in generic classes

src/Unitverse.Core.Tests/Frameworks/FrameworkPackageProviderTests.cs, src/Unitverse.Core.Tests/Models/ProjectCreationManifestTests.cs, src/Unitverse.Core.Tests/Options/Editing/EditableItemExtractorTests.cs, src/Unitverse.Core/Frameworks/FrameworkPackageProvider.cs, src/Unitverse.Core/Models/ProjectCreationManifest.cs, src/Unitverse.Core/Options/Editing/EditableItemExtractor.cs, src/Unitverse.Core/Options/UnitTestGeneratorOptionsFactory.cs, src/Unitverse/Commands/CreateTestProjectCommand.cs, src/Unitverse/Helper/ProjectMappingFactory.cs, src/Unitverse/Helper/ReferencesHelper.cs, src/Unitverse/Helper/SolutionUtilities.cs, src/Unitverse/Helper/WaitableActionHelper.cs, src/Unitverse/IUnitTestGeneratorPackage.cs, src/Unitverse/Properties/Strings.Designer.cs, src/Unitverse/Properties/Strings.resx, src/Unitverse/Resources/DefaultProjectContent.txt, src/Unitverse/UnitTestGeneratorPackage.cs, src/Unitverse/UnitTestGeneratorPackage.vsct, src/Unitverse/Unitverse.csproj, src/Unitverse/Views/ConfigEditorControlViewModel.cs, src/Unitverse/Views/NewProjectDialog.xaml, src/Unitverse/Views/NewProjectDialog.xaml.cs, src/Unitverse/Views/NewProjectDialogViewModel.cs, src/Unitverse/Views/SharedResources.xaml
Adding the ability to create unit test projects by right clicking on project nodes in the solution explorer
Addresses #113 (partly)
=> Project creation

src/Unitverse/Helper/ReferencesHelper.cs, src/Unitverse/IUnitTestGeneratorPackage.cs, src/Unitverse/UnitTestGeneratorPackage.cs, src/Unitverse/Unitverse.csproj, src/Unitverse/Views/NewProjectDialog.xaml.cs
=> Fixing VS2022 compatibility with package versions

src/Unitverse.Core.Tests/Helpers/AssignmentValueHelperTests.cs, src/Unitverse.Core.Tests/Resources/XmlComments.txt, src/Unitverse.Core.Tests/Strategies/ValueGeneration/ValueGenerationStrategyFactoryTester.cs, src/Unitverse.Core/Helpers/Generate.cs, src/Unitverse.Core/Strategies/ValueGeneration/ValueGenerationStrategyFactory.cs, src/Unitverse/Unitverse.csproj
Addresses #121 and adds better default value generation for Task and Task<T>.
=> Enhancements to default value generation

src/.editorconfig, src/Unitverse.Core.Tests/Models/ProjectCreationManifestTests.cs, src/Unitverse.Core.Tests/Resources/NullableReferenceTypes.txt, src/Unitverse.Core.Tests/Strategies/ValueGeneration/ValueGenerationStrategyFactoryTester.cs, src/Unitverse.Core/Models/ParameterModel.cs, src/Unitverse.Core/Strategies/ClassLevelGeneration/NullParameterCheckConstructorGenerationStrategy.cs, src/Unitverse.Core/Strategies/ClassLevelGeneration/StringParameterCheckConstructorGenerationStrategy.cs, src/Unitverse.Core/Strategies/MethodGeneration/NullParameterCheckMethodGenerationStrategy.cs, src/Unitverse.Core/Strategies/MethodGeneration/StringParameterCheckMethodGenerationStrategy.cs, src/Unitverse/Commands/CreateTestProjectCommand.cs, src/Unitverse/Views/NewProjectDialog.xaml.cs, src/Unitverse/Views/NewProjectDialogViewModel.cs
=> Skipping null tests for parameters that explicitly declare a default or null value

src/Unitverse.Core/Helpers/NameExtractor.cs
=> Support for file scoped name spaces

src/Unitverse.Core.Tests/Resources/PartialClasses.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core.Tests/UnitTestRegenerationTests.cs, src/Unitverse.Core/Helpers/TestableItemExtractor.cs, src/Unitverse.Core/Models/ConstructorModel.cs, src/Unitverse.Core/Models/IConstructorModel.cs
Addresses part of the issue in #132
=> Fix for partial class support

.github/workflows/CI.yml, README.md, docs/index.md
Just adding a support section in the docs
=> Adding a support section to the docs

.github/workflows/CI.yml
=> Build update attempt 3

src/Unitverse.Core.Tests/Strategies/ValueGeneration/ValueGenerationStrategyFactoryTester.cs, src/Unitverse.Core/Strategies/ValueGeneration/ValueGenerationStrategyFactory.cs
=> Adding better default value generation for System.Uri

src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core.Tests/Unitverse.Core.Tests.csproj, src/Unitverse.Core/CoreGenerator.cs, src/Unitverse.Core/Frameworks/FrameworkPackageProvider.cs, src/Unitverse.Core/Frameworks/FrameworkSetFactory.cs, src/Unitverse.Core/Frameworks/Mocking/AutoFixtureMockingAdaptor.cs, src/Unitverse.Core/Frameworks/Mocking/JustMockMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/MoqAutoMockMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/MoqMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/NSubstituteMockingFramework.cs, src/Unitverse.Core/Frameworks/Test/NUnit3TestFramework.cs, src/Unitverse.Core/Helpers/AutoFixtureHelper.cs, src/Unitverse.Core/Helpers/FrameworkDetection.cs, src/Unitverse.Core/Helpers/GenerationContext.cs, src/Unitverse.Core/Helpers/GenerationOptionsExtensions.cs, src/Unitverse.Core/Helpers/MethodSymbolExtensions.cs, src/Unitverse.Core/Helpers/MockHelper.cs, src/Unitverse.Core/Helpers/TestableItemExtractor.cs, src/Unitverse.Core/Options/MockingFrameworkType.cs, src/Unitverse.Core/Strategies/ClassDecoration/RequiresStaGenerationStrategy.cs, src/Unitverse.Core/Strategies/PropertyGeneration/MultiConstructorInitializedPropertyGenerationStrategy.cs, src/Unitverse.Core/Strategies/PropertyGeneration/SingleConstructorInitializedPropertyGenerationStrategy.cs, src/Unitverse.Core/Strategies/ValueGeneration/EnumFactory.cs, src/Unitverse.ExampleGenerator/Program.cs, src/Unitverse.ExampleGenerator/Unitverse.ExampleGenerator.csproj
=> Support for JustMock

.github/workflows/CI.yml, MarketplaceOverview.md, docs/contributing.md, docs/examples/FrameworksFluentAssertions.md, docs/examples/FrameworksMsTestMoq.md, docs/examples/FrameworksMsTestMoqAutoMock.md, docs/examples/FrameworksNUnitFakeItEasy.md, docs/examples/FrameworksXUnitJustMock.md, docs/examples/FrameworksXUnitNSubstitute.md, docs/examples/index.md, docs/index.md, src/Unitverse.ExampleGenerator/Examples.Designer.cs, src/Unitverse.ExampleGenerator/Examples.resx, src/Unitverse.ExampleGenerator/Resources/FrameworksFluentAssertions.txt, src/Unitverse.ExampleGenerator/Resources/FrameworksMsTestMoq.txt, src/Unitverse.ExampleGenerator/Resources/FrameworksMsTestMoqAutoMock.txt, src/Unitverse.ExampleGenerator/Resources/FrameworksNUnitFakeItEasy.txt, src/Unitverse.ExampleGenerator/Resources/FrameworksXUnitJustMock.txt, src/Unitverse.ExampleGenerator/Resources/FrameworksXUnitNSubstitute.txt, src/Unitverse.ExampleGenerator/Resources/FrameworksXUnitNSubstitute1.txt
=> JustMock documentation, some tidy up of examples & docx

.github/workflows/CI.yml
=> Build update to push version into help/about

src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core.Tests/UnitTestRegenerationTests.cs, src/Unitverse.Core/CoreGenerator.cs, src/Unitverse.Core/Helpers/TestableItemExtractor.cs, src/Unitverse.ExampleGenerator/Program.cs, src/Unitverse.Specs/ClassBasedStrategySteps.cs, src/Unitverse/Helper/CodeGenerator.cs
=> Changes to respect VS tab settings on generation

src/Unitverse.Core.Tests/Resources/SealedClassWithProtectedMethod.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/Helpers/TestableItemExtractor.cs, src/Unitverse.Core/Strategies/ClassGeneration/AbstractClassGenerationStrategy.cs, src/Unitverse.Core/Strategies/ClassGeneration/StandardClassGenerationStrategy.cs
=> Fixing generation for sealed classes with protected members

src/Unitverse/Helper/ReferencesHelper.cs, src/Unitverse/Helper/VsProjectHelper.cs
=> Fix for hanging on project creation... hopefully

src/Unitverse/Options/ExportOptionsControl.resx
Update UI text to reflect the real name of the config file: `.unitTestGeneratorConfig`
=> Update UI text to reflect the real name of the config file.

src/Unitverse.Core.Tests/DefaultGenerationOptions.cs, src/Unitverse.Core.Tests/Options/Editing/GenerationOptions.cs, src/Unitverse.Core.Tests/Resources/BaseClassSpecified.txt, src/Unitverse.Core.Tests/Resources/BaseClassSpecifiedExplicitly.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core/CoreGenerator.cs, src/Unitverse.Core/Helpers/DetectedGenerationOptions.cs, src/Unitverse.Core/Helpers/Generate.cs, src/Unitverse.Core/Options/IGenerationOptions.cs, src/Unitverse.Core/Options/MutableGenerationOptions.cs, src/Unitverse.Core/Strategies/ClassGeneration/ClassGenerationStrategyFactory.cs, src/Unitverse.Core/Strategies/ClassGeneration/StaticClassGenerationStrategy.cs, src/Unitverse.ExampleGenerator/DefaultGenerationOptions.cs, src/Unitverse.Specs/GenerationOptions.cs, src/Unitverse/Helper/CodeGenerator.cs, src/Unitverse/Options/GenerationOptions.cs
=> Implementation of target asset suppression and base class specification

src/Unitverse/Helper/CodeGenerator.cs
=> Fixing stupid mistake

src/Unitverse.Core.Tests/RegenerationTestClasses.Designer.cs, src/Unitverse.Core.Tests/RegenerationTestClasses.resx, src/Unitverse.Core.Tests/Resources/Regeneration-FileScopedUsingsOutside.txt, src/Unitverse.Core.Tests/Resources/Regeneration-FileScopedUsingsOutsideMultipleClasses.txt, src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core.Tests/UnitTestRegenerationTests.cs, src/Unitverse.Core/Generation/BlockScopedNamespaceStrategy.cs, src/Unitverse.Core/Generation/BlockScopedNamespaceStrategyBootstrapper.cs, src/Unitverse.Core/Generation/CompilationUnitStrategy.cs, src/Unitverse.Core/Generation/FileScopedNamespaceStrategy.cs, src/Unitverse.Core/Generation/FileScopedNamespaceStrategyBootstrapper.cs, src/Unitverse/Options/GenerationOptions.cs
Slight refactor of the compilation unit strategies, ability to control using position with file scoped namespaces
=> Ability to control using position with file scoped namespaces

docs/examples/RecordTypeInitProperties.md, src/Unitverse.Core.Tests/Resources/IEnumerableParameters.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/Frameworks/Mocking/MoqAutoMockMockingFramework.cs, src/Unitverse.Core/Generation/TypeDeclarationFactory.cs, src/Unitverse.Core/Helpers/Generate.cs, src/Unitverse.Core/Helpers/TypeInfoExtensions.cs, src/Unitverse.Core/Models/ClassModel.cs
=> Making IEnumerable constructor parameters receive an implicitly typed array

src/Unitverse.Core.Tests/UnitTestRegenerationTests.cs, src/Unitverse.Core/Generation/BlockScopedNamespaceStrategy.cs, src/Unitverse.Core/Generation/CompilationUnitStrategy.cs, src/Unitverse.Core/Generation/FileScopedNamespaceStrategy.cs
=> Fix for regeneration on top of file scoped namespaces

docs/configuration.md, src/Unitverse/Helper/OptionsResolver.cs, src/Unitverse/Helper/ProjectMappingFactory.cs
Small clarifications to resolve #192
=> Updates to clarify options when 'detect target frameworks' is enabled.

src/Unitverse/Manifests/VS2022/source.extension.vsixmanifest, src/Unitverse/Unitverse.csproj
=> Add arm64 Visual Studio support

src/Unitverse.Core/Resources/PropertyTesterMSTest.txt, src/Unitverse.Core/Resources/PropertyTesterNUnit.txt, src/Unitverse.Core/Resources/PropertyTesterXUnit.txt
Based on https://github.com/mattwhitfield/Unitverse/issues/196
=> Changed PropertyTester to allow using non-public getters and setters

src/Unitverse.Core.Tests/Resources/AutomaticMockThis.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core.Tests/Unitverse.Core.Tests.csproj, src/Unitverse.Core/Helpers/InvocationExtractor.cs
Support for this. syntax while extracting mockable invocations
Resolves #198
=> Support for this. syntax while extracting mockable invocations

src/Unitverse.Core.Tests/Helpers/TestableItemExtractorTests.cs, src/Unitverse.Core.Tests/Models/ClassModelTests.cs, src/Unitverse.Core.Tests/Options/MutableNamingOptionsTests.cs, src/Unitverse.Core.Tests/TestSemanticModelFactory.cs, src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core/Frameworks/Mocking/MoqAutoMockMockingFramework.cs, src/Unitverse.Core/Generation/TypeDeclarationFactory.cs, src/Unitverse.Core/Helpers/Generate.cs, src/Unitverse.Core/Helpers/TypeInfoExtensions.cs, src/Unitverse.Core/Models/ClassModel.cs, src/Unitverse.Core/Options/INamingOptions.cs, src/Unitverse.Core/Options/INamingProvider.cs, src/Unitverse.Core/Options/MutableNamingOptions.cs, src/Unitverse.Core/Options/NamingProvider.cs, src/Unitverse.Tests.Common/DefaultFrameworkSet.cs, src/Unitverse.Tests.Common/DefaultNamingOptions.cs, src/Unitverse/Options/NamingOptions.cs
=> Ability to specify a different field name pattern for mocked dependencies

src/Unitverse.Core/Strategies/ClassGeneration/ClassGenerationStrategyFactory.cs, src/Unitverse/Commands/GenerationItem.cs, src/Unitverse/Helper/ProjectItemModel.cs, src/Unitverse/Helper/TargetFinder.cs, src/Unitverse/Helper/VsProjectHelper.cs
=> Changes to support nested files

src/Unitverse.Core.Tests/Resources/AsyncMethod.txt, src/Unitverse.Core/Frameworks/Test/BaseTestFramework.cs, src/Unitverse.Core/Options/INamingOptions.cs, src/Unitverse.Core/Options/INamingProvider.cs, src/Unitverse.Core/Options/MutableNamingOptions.cs, src/Unitverse.Core/Options/NamingProvider.cs, src/Unitverse.Core/Templating/ITemplatingContext.cs, src/Unitverse.Tests.Common/DefaultNamingOptions.cs, src/Unitverse/Options/NamingOptions.cs
=> Option to force test method names to end with Async when they are async

docs/examples/FrameworksNUnitLifecycleNSubstitute.md, docs/examples/index.md, src/Unitverse.Core.Tests/Frameworks/Test/TestFrameworkTests.cs, src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core/Assets/PropertyTesterAsset.cs, src/Unitverse.Core/Frameworks/FrameworkPackageProvider.cs, src/Unitverse.Core/Frameworks/FrameworkSetFactory.cs, src/Unitverse.Core/Frameworks/ITestFramework.cs, src/Unitverse.Core/Frameworks/Test/MsTestTestFramework.cs, src/Unitverse.Core/Frameworks/Test/NUnit3LifeCycleFramework.cs, src/Unitverse.Core/Frameworks/Test/NUnit3TestFramework.cs, src/Unitverse.Core/Frameworks/Test/NUnitTestFramework.cs, src/Unitverse.Core/Frameworks/Test/XUnitTestFramework.cs, src/Unitverse.Core/Helpers/Generate.cs, src/Unitverse.Core/Options/TestFrameworkTypes.cs, src/Unitverse.Core/Strategies/ClassGeneration/AbstractClassGenerationStrategy.cs, src/Unitverse.Core/Strategies/ClassGeneration/StandardClassGenerationStrategy.cs, src/Unitverse.Core/Strategies/ClassGeneration/StaticClassGenerationStrategy.cs, src/Unitverse.ExampleGenerator/Examples.Designer.cs, src/Unitverse.ExampleGenerator/Examples.resx, src/Unitverse.ExampleGenerator/Program.cs, src/Unitverse.ExampleGenerator/Resources/FrameworksNUnitLifeCycleNSubstitute.txt
=> Support for NUnit3 (Lifecycle)

src/Unitverse.Core.Tests/Resources/OmitTestClassAttribute.txt, src/Unitverse.Core.Tests/Resources/UseConstructorForClassSetup.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/Frameworks/Test/MsTestTestFramework.cs, src/Unitverse.Core/Frameworks/Test/NUnitTestFramework.cs, src/Unitverse.Core/Helpers/DetectedGenerationOptions.cs, src/Unitverse.Core/Helpers/FrameworkSetHelper.cs, src/Unitverse.Core/Options/IGenerationOptions.cs, src/Unitverse.Core/Options/MutableGenerationOptions.cs, src/Unitverse.Core/Strategies/ClassGeneration/AbstractClassGenerationStrategy.cs, src/Unitverse.Core/Strategies/ClassGeneration/StandardClassGenerationStrategy.cs, src/Unitverse.Core/Strategies/ClassGeneration/StaticClassGenerationStrategy.cs, src/Unitverse.Tests.Common/DefaultGenerationOptions.cs, src/Unitverse/Options/GenerationOptions.cs
=> Fixture life cycle and ability to omit test class attributes

docs/examples/FrameworksMsTestMoqAutoMock.md, src/Unitverse.Core.Tests/Resources/UnmanagedConstraint.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core.Tests/UnitTestGeneratorTests.cs, src/Unitverse.Core/Frameworks/IMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/AutoFixtureMockingAdaptor.cs, src/Unitverse.Core/Frameworks/Mocking/FakeItEasyMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/JustMockMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/MoqAutoMockMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/MoqMockingFramework.cs, src/Unitverse.Core/Frameworks/Mocking/NSubstituteMockingFramework.cs, src/Unitverse.Core/Generation/CompilationUnitStrategy.cs, src/Unitverse.Core/Models/ClassModel.cs
Title kind of says it all
Resolves #248
=> Adding support for emitting against generic type contraints struct / unmanaged

src/Unitverse/Helper/VsProjectHelper.cs
=> Fixing use of empty RootNamespace tags

src/Unitverse.Core.Tests/Resources/NullOrWhiteSpaceSeparation.txt, src/Unitverse.Core.Tests/TestClasses.Designer.cs, src/Unitverse.Core.Tests/TestClasses.resx, src/Unitverse.Core/Helpers/DetectedGenerationOptions.cs, src/Unitverse.Core/Helpers/GenerationOptionsExtensions.cs, src/Unitverse.Core/Options/IGenerationOptions.cs, src/Unitverse.Core/Options/MutableGenerationOptions.cs, src/Unitverse.Core/Strategies/ClassLevelGeneration/StringParameterCheckConstructorGenerationStrategy.cs, src/Unitverse.Core/Strategies/MethodGeneration/StringParameterCheckMethodGenerationStrategy.cs, src/Unitverse.Tests.Common/DefaultGenerationOptions.cs, src/Unitverse/Options/GenerationOptions.cs
=> Adding the ability to emit separate null / invalid string checks

src/Unitverse.Core/Options/UnitTestGeneratorOptionsFactory.cs, src/Unitverse/Options/ExportOptionsControl.Designer.cs, src/Unitverse/Options/ExportOptionsControl.cs, src/Unitverse/Options/ExportOptionsControl.resx, src/Unitverse/UnitTestGeneratorPackage.cs
=> Added ability to import settings
